![imagen](./img/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden, usando numpy.

In [6]:
my_array = np.arange(0, 10)

print(np.flip(my_array[my_array % 2 != 0]))

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [13]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [8]:
print(np.flip(my_array[:3:]))

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [4]:
my_matrix = np.arange(1, 21).reshape(4, 5) 
print(my_matrix)
print()
print(np.flip(my_matrix))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [ ]:
print(my_matrix[:2, :2])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [43]:
print(my_matrix[::2, ].copy()[matrix % 2 != 0].reshape(2, 3))

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [9]:
print(np.flip(my_matrix[0:3].copy(), axis = 1))

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [53]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

#1 Pasandole la mascara
mask = x == "Loro"
print(x[mask])

#2 Pasandole los indices donde aparece "Loro"
indexes = np.where(x == "Loro")
print(x[indexes])

['Loro' 'Loro']
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [54]:
print(np.arange(0, 20).reshape(2, 5, 2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [173]:
zeros = np.zeros(10, dtype=int)
print(zeros.nbytes)
zeros[3] = 1
print(zeros)

80
[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [58]:
print(np.flip(np.arange(10, 50))) 

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [63]:
def non_zero(x):
    return x[x != 0]

print(non_zero(np.array([1,2,0,0,4,0])))

[1 2 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [111]:
rm = np.random.randint(1, 10001, (10, 10))
print(rm)
print()
print("Max: %d\nMin: %d" % (np.max(rm), np.min(rm)))

[[4360 3358 3192 2538 4012 7525 3053 1207 8622 8467]
 [1789 7103 2169  909 6327 3635 5988  859 4890 6242]
 [1193 6581 3856 6227  925 1163 2806 5930 6240 3737]
 [3177 7297 7459 2863 9681 6903 2183 9022 7342 9966]
 [4963 4979 5679 7901  209 6115 1732 4107 4872  219]
 [1402 6202 1765 5747 3935 7609 3151 8352 4621 6454]
 [6683 8087  125 3792 2999  786 5041 4512 6412 9147]
 [7712 5224 6286 3630 2346 9420 6060 2201  805 5905]
 [ 220 3345 1582 9637 8697  261 2306 1221 9996 7662]
 [6986  719 9341 2013 8584  565 7931 4211 8418 9800]]

Max: 9996
Min: 125


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [10]:
vec = np.random.randint(1, 10001, 30)
print("Media: %.2f" % (vec.mean()))

Media: 4722.20


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [14]:
def padding_func(vector, iaxis_pad_width, iaxis, kwargs):
    pad_value = kwargs.get('padder', 1)
    vector[:iaxis_pad_width[0]] = pad_value
    vector[-iaxis_pad_width[1]:] = pad_value
    
a = np.zeros(5*5, dtype=int)
a = a.reshape((5, 5))
np.pad(a, 1, padding_func)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [16]:
dim_array = 6
matriz_15 = np.zeros((dim_array, dim_array), dtype=int)
matriz_15[0,:] = 1
matriz_15[-1,:] = 1
matriz_15[:, 0] = 1
matriz_15[:, -1] = 1

print(matriz_15)


[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [20]:
m = np.ones((6,6), dtype=int)
m[1:-1, 1:-1] = 0
print(m)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [140]:
patron = np.ones((8, 8), dtype=int)
patron[::2,::2] = 0
patron[1::2, 1::2] = 0
print(patron)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [26]:
patron2 = np.ones((8, 8), dtype=int)
matriz = np.tile([[0,1], [1,0]], (4,4))
print(matriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [152]:
mat = np.random.randint(0, 5, (5,5))

print((mat - mat.mean())/mat.std())

[[ 1.04342253 -0.22904397 -1.50151047  1.04342253 -1.50151047]
 [-0.22904397 -1.50151047  1.04342253 -0.86527722 -1.50151047]
 [ 0.40718928 -1.50151047  1.04342253  0.40718928  1.04342253]
 [ 0.40718928  1.04342253  0.40718928  1.04342253  0.40718928]
 [-0.86527722  0.40718928  0.40718928  1.04342253 -1.50151047]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [27]:
seq = np.arange(11)
print(seq)
seq[(seq >= 3) & (seq <= 8)] = -1
print(seq)
seq = np.arange(11)
mask = (seq >= 3) & (seq <= 8)
seq[mask] = -seq[mask]
print(seq)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [30]:
array_19 = np.where((seq > 3) & (seq < 8), -1, seq)
array_19 = np.where((seq > 3) & (seq < 8), -seq, seq)
print(array_19)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
